version: '3.0'
services:
  thream-website:
    build:
      context: './'
    ports:
      - '3000:3000'
    volumes:
      - './:/app'
      - '/app/node_modules'
      - '/app/.next'
    container_name: 'thream-website'
